version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 07072005
      POSTGRES_DB: RecieptSplit
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go_server:
    build:
      context: ./go_server
    env_file:
      - ./go_server/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - go_server
    env_file:
      - ./go_server/.env

volumes:
  pgdata:
